name: AKSI PSI Publish
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish latest psi manifest into docs/
        run: |
          mkdir -p docs/data
          test -f aksi_psihub/psi_manifest.json && cp aksi_psihub/psi_manifest.json docs/data/manifest.json || true
          printf '{\n  \"generated_at\": \"%s\"\n}' "$(date -u +%FT%TZ)" > docs/data/meta.json
      - name: Commit docs data
        run: |
          git config user.name "AKSI Bot"
          git config user.email "aksi-bot@example.com"
          git add docs/data/*
          git commit -m "docs: publish latest psi manifest" || echo 'no changes'
          git push
